package edu.uky.cs.nil.sabre.prog;

import edu.uky.cs.nil.sabre.Character;
import edu.uky.cs.nil.sabre.State;
import edu.uky.cs.nil.sabre.comp.CompiledAction;
import edu.uky.cs.nil.sabre.comp.CompiledProblem;
import edu.uky.cs.nil.sabre.logic.Value;

/**
 * A progression node represents a node in a {@link ProgressionSpace search
 * space} and its context in a {@link ProgressionSearch progression search},
 * such as the temporal and epistemic depth at which the node exists in that
 * search. The same node in a search space might be reached at different times
 * and in different ways during different search methods. Likewise, the same
 * search might find the same node in a search space multiple times but at
 * different temporal or epistemic depths. A progresison node is a reference
 * both to the search space node and to how and when it was reached in a
 * particular search.
 * 
 * @param <N> the type of object used to represent a node in {@link
 * ProgressionSpace the search space}
 * @author Stephen G. Ware
 */
public interface ProgressionNode<N> extends State {

	/**
	 * Returns the {@link CompiledProblem problem} the search that generated
	 * this node is solving.
	 * 
	 * @return the problem being solved by the search that generated this node
	 */
	public default CompiledProblem getProblem() {
		return getSearch().problem;
	}
	
	/**
	 * Returns the {@link ProgressionSearch search} that generated this node.
	 * 
	 * @return the search that generated this node
	 */
	public ProgressionSearch getSearch();
	
	/**
	 * Returns the {@link ProgressionSpace search space} the search that
	 * generated this node is using. The {@link #getNode() search space node}
	 * associated with this progression node will be a node in that space.
	 * 
	 * @return the search space used by the search that generated this node
	 */
	@SuppressWarnings("unchecked")
	public default ProgressionSpace<N> getSpace() {
		return (ProgressionSpace<N>) getSearch().space;
	}
	
	/**
	 * Returns the {@link Character character} whose utility the search that
	 * produced this node was trying to improve when this node was generated.
	 * 
	 * @return the character whose utility the search was trying to improve when
	 * this node was generated
	 */
	public Character getCharacter();
	
	/**
	 * Returns this node's trunk, which is a {@link ProgressionSpace search
	 * space} node that represents the original action that was being explained
	 * when the search generated this node. When a {@link ProgressionSearch
	 * progression search} adds an action to a plan, it must explain that action
	 * for each of its consenting characters by creating branches for each one.
	 * A branch is the state that character believes will be the case after
	 * taking the action; the state after the original action from which the
	 * branches extend is the trunk for all of those branches. The primary
	 * search to improve the author's utility has no trunk, and this method will
	 * return null for those nodes.
	 * 
	 * @return the trunk node that the search was explaining when this node was
	 * created, or null if this node is part of the search to improve the
	 * author's utility
	 */
	public N getTrunk();
	
	/**
	 * Returns the root from which this node is a temporal descendant, which is
	 * a {@link ProgressionSpace search space} node that represents where the
	 * search that generated this node started. When a {@link ProgressionSearch
	 * progression search} adds an action to a plan, it must explain the action
	 * for each of its consenting characters by creating branches for each one.
	 * A branch starts in the state that character believes will be the case
	 * after taking the action; this starting state is called the root. The root
	 * node is one which, if explained, would mean the original {@link
	 * #getTrunk() trunk node} is also explained for one of its consenting
	 * characters.
	 * 
	 * @return the root node where the search began to explain an action for
	 * a character and which caused this node to be generated
	 */
	public N getRoot();
	
	/**
	 * Returns the {@link ProgressionSpace#getAction(Object) action} associated
	 * with this node's {@link #getNode() search space node}.
	 * 
	 * @return the action associated with this node's search space node
	 */
	public default CompiledAction getAction() {
		return getSpace().getAction(getNode());
	}
	
	/**
	 * Returns the node from the {@link ProgressionSpace search space} that this
	 * progression node is referring to. A progression node is a reference to
	 * a node in the {@link #getSearch() search's} {@link #getSpace() space}
	 * (accessed with this method), but annotated with the context in which it
	 * was generated by the search.
	 * 
	 * @return the search space node associated with this progression node
	 */
	public N getNode();
	
	/**
	 * Returns whether or not the {@link #getNode() search space node} that this
	 * progression node refers to is {@link ProgressionSpace#isExplained(Object)
	 * explained} for all the characters for which it needs to be explained.
	 * Usually, a node needs to be explained for all of the {@link
	 * CompiledAction#consenting consenting characters} of {@link #getAction()
	 * the action} that led to the state the node represents. However, there is
	 * one special case: {@link #getRoot() a root node}. A root node is created
	 * to explain one action ({@link #getTrunk() the trunk}) for one character.
	 * This means that a root node only needs to be explained for the character
	 * it was created to explained, even if the action has more than one
	 * consenting character. If this progression node is a root, this method
	 * will return true if it is explained {@link #getCharacter() for its
	 * character}, no matter how many consenting characters the action may have.
	 * 
	 * @return true if the node is explained for all its consenting characters
	 * or if the node is a root node and is explained for the character that
	 * root node was created to explain; false otherwise
	 */
	public default boolean isExplained() {
		if(getTemporalDepth() == 0)
			return isExplained(getCharacter());
		else
			return getSpace().isExplained(getNode());
	}
	
	/**
	 * Returns whether or not the {@link #getNode() search space node} that this
	 * progression node refers to is {@link
	 * ProgressionSpace#isExplained(Object, Character) explained for the given
	 * character}. In some implementations, this method will return false if
	 * the character is not a consenting character to {@link #getAction() the
	 * node's action}, even if that character would want the action to happen.
	 * 
	 * @param character the character for whom the node may be explained
	 * @return true if the node is explained for that character
	 */
	public default boolean isExplained(Character character) {
		return getSpace().isExplained(getNode(), character);
	}
	
	/**
	 * Returns the utility of a given character (or the author, if the character
	 * is null) in the state represented by this progression node's {@link
	 * #getNode() search space node}.
	 * 
	 * @param character the character whose utility is desired, or null if the
	 * author's utility is desired
	 * @return the utility of that character in that state this node represents
	 */
	public default Value getUtility(Character character) {
		if(character == null)
			return getProblem().utility.evaluate(this);
		else
			return getProblem().utilities.get(character).evaluate(this);
	}
	
	/**
	 * Returns the number of actions that have been taken since the initial
	 * state, regardless of this node's {@link #getEpistemicDepth() epistemic
	 * depth}. For author nodes (epistemic depth 0), this value is the same as
	 * {@link #getPlanLength() plan length}. For character nodes (epistemic
	 * depth > 0), this value includes any actions that occurred before the
	 * {@link #getRoot() root node} (even if the character did not observe
	 * them), the action leading to the root node, and all actions that have
	 * occurred since the root node.
	 * 
	 * @return the number of actions taken since the initial state
	 */
	public int getTemporalDepth();
	
	/**
	 * Returns the number of actions that have been taken since the explanation
	 * this node is part of began. For author nodes ({@link #getEpistemicDepth()
	 * epistemic depth} 0), this value is the same as {@link #getPlanLength()
	 * plan length}. For nodes with epistemic depth 1 (nodes created to explain
	 * author nodes), this value is also the same as plan length, regardless of
	 * where in the author's plan the action being explained occurs, because
	 * explanation length does not depend on the length of the author's plan.
	 * For nodes with epistemic depth > 1, this value includes any actions taken
	 * at lower epistemic depths.
	 * <p>
	 * For example, say the author's plan is actions A then B. After the second
	 * action (B), explanation depth is the same as plan length, which is 2.
	 * Now suppose a branch is created with B as the {@link #getTrunk() trunk}.
	 * This branch has an epistemic depth of 1. That node will have an
	 * explanation depth and plan length of 1 because action B is the first
	 * action in the branch (action B and the state after taking it form the
	 * root node of the new search). From that root, say two more actions C and
	 * D are taken. The state after D has an explanation depth of 3 (the root B
	 * + the two actions that have been taken since the root). Now suppose a
	 * branch is created with D as the trunk and an epistemic depth of 2. From
	 * there, two more actions E and F are taken. The state after F has a plan
	 * length of 3 (the root D + the two actions that have been taken since the
	 * root) but an explanation depth of 5, because it also counts actions B, C,
	 * and D from epistemic depth 1.
	 * <p>
	 * Explanation depth is defined this way so that a search can have a {@link
	 * edu.uky.cs.nil.sabre.search.Search#characterTemporalLimit character
	 * temporal limit} which is different from its {@link
	 * edu.uky.cs.nil.sabre.search.Search#authorTemporalLimit author temporal
	 * limit} without creating an infinitely deep space.
	 * <p>
	 * A search will only expand an author node (epistemic depth 0) if its
	 * explanation depth is less than the search's author temporal limit. A
	 * search will only expand a character node (epistemic depth > 0) if its
	 * explanation depth is less than the search's character temporal limit.
	 * 
	 * @return the number of actions taken since the explanation began
	 */
	public int getExplanationDepth();
	
	/**
	 * Returns the number of actions that have been taken in the plan leading to
	 * this node. The only node with a plan length of 0 is the author root node
	 * of the search. The children of the author root node have a plan length of
	 * 1, their children a plan length of 2, and so on. For character nodes
	 * ({@link #getEpistemicDepth() epistemic depth} > 0), this number will
	 * always be at least 1, because it will include the first action leading to
	 * the search's {@link #getRoot() root node}. In other words, for character
	 * nodes, the plan length is always 1 + the number of actions that have been
	 * taken since the root node.
	 * 
	 * @return the number of actions taken in the plan to reach this node
	 */
	public int getPlanLength();
	
	/**
	 * Returns the depth of nested theory of mind (what one {@link Character
	 * character} believes another character believes, and so on) at which this
	 * node was created. All nodes have the same epistemic depth as their {@link
	 * #getRoot() root}, which is always 1 higher than their {@link #getTrunk()
	 * trunk}. A node will only be visited if its epistemic depth is less than
	 * or equal to {@link ProgressionSearch#epistemicLimit the search's
	 * epistemic limit}.
	 * 
	 * @return the depth of theory of mind at which this node was created
	 */
	public int getEpistemicDepth();
}